#!/usr/bin/python
from seqdata import getset
from sklearn.model_selection import train_test_split
import matplotlib.pylab as plt
import sklearn
import numpy
import random
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression

#sklearn.show_versions()

X,y=getset(7)
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=1234567, shuffle=True)

model=AdaBoostClassifier(n_estimators=500)#,base_estimator=LogisticRegression(max_iter=500,multi_class="multinomial",), learning_rate=0.1)
model.fit(X_train, y_train)
yp=model.predict(X_test)
print (sklearn.metrics.accuracy_score(y_test,yp))

yp=model.predict(X_train)
print (sklearn.metrics.accuracy_score(y_train,yp))

cm=confusion_matrix(y_train,yp)
plt.imshow(numpy.log(cm))
plt.show()
#proba=model1.predict_proba(X_train)

print (model.estimators_)
print (model.estimator_errors_)
print (model.estimator_weights_)
print (model.n_features_in_)