#!/usr/bin/python
from seqdata import getset
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

X,y=getset(7)
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=1234567, shuffle=True)

model=LogisticRegression(solver="saga")
model.fit(X_train, y_train)
print (model.score(X_train, y_train))
print (model.score(X_test, y_test))

